# GitHub Action that uploads our new website content to S3 when we push to GitHub

name : Upload website to S3                     # You can name the workflow anything

on:                                             # Specifies when the workflow should trigger
    push:                                       # This workflow runs when we push code
        branches:
        - main                                  # triggered when there is a push on the main branch

jobs:                                           # defines the tasks this workflow will perform
    deploy:                                     # Defines the job named 'deploy'
        runs-on: ubuntu-latest                  # The job will run on an Ubuntu virtual machine

        steps:
        # Step 1: Checkout code from the GitHub repository
        - uses: actions/checkout@master         # Fetches the latest code from the repo

        # Step 2: Move and clean up files
        - run: |
            mv MyResume-1.0.0/* .               # Move all files from 'MyResume-1.0.0' folder to root
            rm -r MyResume-1.0.0                # Delete the now-empty folder
            ls -la                              # List files in the directory (for debugging)

        # Step 3: Sync files to S3 using jakejarvis/s3-sync-action    
        - uses: jakejarvis/s3-sync-action@master
          with:
                args: --acl private --follow-symlinks --delete --exclude '.git/*'
                    # --acl private: Makes uploaded files private
                    # --follow-symlinks: Follows symbolic links if any
                    # --delete: Removes files from S3 that are no longer in the repository
                    # --exclude '.git/*': Prevents the '.git' directory from being uploaded

        # Step 4: Define environment variables            
        env:
            # Name of the S3 bucket
            AWS_S3_BUCKET: cloud-resume-hkmmb

            # AWS Access Key (from GitHub Secrets)
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

            # AWS Secret Key (from GitHub Secrets)
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            # AWS region of the S3 bucket
            AWS_REGION: 'ap-southeast-1'

            # The folder containing files to upload (root directory)
            SOURCE: .